config/routes.rb
Rails.application.routes.draw do
  resources :reposts
  resources :likes
  root 'posts#index'
  resources :posts
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :relationships, only: [:index, :create, :destroy] do
    collection do
      get 'who_to_follow'
      get 'followers'
      get 'followings'
    end
  end
  get '/:username', to: 'posts#user_timeline', as: :user_timeline
end

app/models/repost.rb
class Repost < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :post, uniqueness: { scope: :user}
end

app/controllers/reposts_controller.rb
class RepostsController < ApplicationController
  before_action :set_repost, only: [:show, :edit, :update, :destroy]

  # GET /reposts
  # GET /reposts.json
  def index
    @reposts = Repost.all
  end

  # GET /reposts/1
  # GET /reposts/1.json
  def show
  end

  # POST /reposts
  # POST /reposts.json
  def create
    @repost = Repost.new(repost_params)

    respond_to do |format|
      if @repost.save
        format.html {redirect_to :back}
      end
    end
  end

  # DELETE /reposts/1
  # DELETE /reposts/1.json
  def destroy
    @repost.destroy
    respond_to do |format|
      format.html {redirect_to :back }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_repost
    @repost = Repost.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def repost_params
    params.require(:repost).permit(:post_id, :user_id)
  end
end

app/helpers/reposts_helper.rb
module RepostsHelper
end

app/views/reposts/_form.html.erb
<%= form_for(repost) do |f| %>
  <% if repost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repost.errors.count, "error") %> prohibited this repost from being saved:</h2>

      <ul>
      <% repost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %>
    <%= f.number_field :post_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reposts/edit.html.erb
<h1>Editing Repost</h1>

<%= render 'form', repost: @repost %>

<%= link_to 'Show', @repost %> |
<%= link_to 'Back', reposts_path %>

app/views/reposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reposts</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reposts.each do |repost| %>
      <tr>
        <td><%= repost.post_id %></td>
        <td><%= repost.user_id %></td>
        <td><%= link_to 'Show', repost %></td>
        <td><%= link_to 'Edit', edit_repost_path(repost) %></td>
        <td><%= link_to 'Destroy', repost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repost', new_repost_path %>

app/views/reposts/new.html.erb
<h1>New Repost</h1>

<%= render 'form', repost: @repost %>

<%= link_to 'Back', reposts_path %>

app/views/reposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @repost.post_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @repost.user_id %>
</p>

<%= link_to 'Edit', edit_repost_path(@repost) %> |
<%= link_to 'Back', reposts_path %>