config/routes.rb
Rails.application.routes.draw do
  resources :reposts
  resources :likes
  root 'posts#index'
  resources :posts
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :relationships, only: [:index, :create, :destroy] do
    collection do
      get 'who_to_follow'
      get 'followers'
      get 'followings'
    end
  end
  get '/:username', to: 'posts#user_timeline', as: :user_timeline
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User', foreign_key: :user_id
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  # GET /relationships
  # GET /relationships.json
  def index
    @relationships = Relationship.all
  end

  def who_to_follow
    @to_follows = current_user.who_to_follow
  end

  def followers
    @followers = current_user.followers
  end

  def followings
    @followings = current_user.followings
  end

  # POST /relationships
  # POST /relationships.json
  def create
    @relationship = Relationship.new(relationship_params)

    respond_to do |format|
      # TODO: Handle relationship creation error
      if @relationship.save
        format.html {redirect_to :back}
        format.json {render :show, status: :created, location: @relationship}
      end
    end
  end

  # DELETE /relationships/1
  # DELETE /relationships/1.json
  def destroy
    # TODO: Handle relationship destroy error

  @relationship = Relationship.find_by!(relationship_params)
    @relationship.destroy

    respond_to do |format|
      format.html {redirect_to :back}
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def relationship_params
    params.require(:relationship).permit(:follower_id, :user_id)
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follower.html.erb
<li class="media mt-2 px-3 pb-2" style="border-bottom: 1px solid rgba(0, 0, 0, 0.125);">
  <%= image_tag follower.avatar_url(120), size: '40x40', class: 'mr-3 rounded-circle' %>
  <div class="media-body">
    <div>
      <span class="mt-0 mb-1 h6" style="
      font-size: 14px;
      "><%= link_to(follower.fullname, user_timeline_path(follower.moniker), style: "color: #009688;") %></span>
      <%= link_to('@' + follower.moniker, user_timeline_path(follower.moniker), style: "color: #009688;") %>
    </div>

    <%= follower.description %>
  </div>
</li>

app/views/relationships/_following.html.erb
<li class="media mt-2 px-3 pb-2" style="border-bottom: 1px solid rgba(0, 0, 0, 0.125);">
  <%= image_tag following.avatar_url(120), size: '40x40', class: 'mr-3 rounded-circle' %>
  <div class="media-body">
    <div>
      <span class="mt-0 mb-1 h6" style="
      font-size: 14px;
      "><%= link_to(following.fullname, user_timeline_path(following.moniker), style: "color: #009688;") %></span>
      <%= link_to('@' + following.moniker, user_timeline_path(following.moniker), style: "color: #009688;") %>
    </div>

    <%= following.description %>
  </div>
  <%= form_for Relationship.find_by!(user_id: following.id, follower_id: current_user.id), method: :delete do |f| %>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :follower_id %>
    <%= f.submit("Following", class: "btn btn-outline-danger py-0 mt-2", style: "border-radius: 1rem; font-size: 13px;") %>
  <% end %>
</li>

app/views/relationships/_form.html.erb
<%= form_for(relationship) do |f| %>
  <% if relationship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(relationship.errors.count, "error") %> prohibited this relationship from being saved:</h2>

      <ul>
      <% relationship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :follower_id %>
    <%= f.text_field :follower_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relationships/_to_follow.html.erb
<li class="media mt-2 px-3 pb-2" style="border-bottom: 1px solid rgba(0, 0, 0, 0.125);">
  <%= image_tag to_follow.avatar_url(120), size: '40x40', class: 'mr-3 rounded-circle' %>
  <div class="media-body">
    <div>
      <span class="mt-0 mb-1 h6" style="
      font-size: 14px;
      "><%= link_to(to_follow.fullname, user_timeline_path(to_follow.moniker), style: "color: #009688;") %></span>
      <%= link_to('@' + to_follow.moniker, user_timeline_path(to_follow.moniker), style: "color: #009688;") %>
    </div>

    <%= to_follow.description %>

  </div>
  <%= form_for Relationship.new(user_id: to_follow.id, follower_id: current_user.id) do |f| %>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :follower_id %>
    <%= f.submit("Follow", class: "btn btn-outline-success py-0 mt-2", style: "border-radius: 1rem; font-size: 13px;") %>
  <% end %>
</li>

app/views/relationships/followers.html.erb
<div class="row">
  <div class="col-3">
    <%= render 'posts/user_card', user: current_user %>
  </div>
  <div class="col-6">
    <ul class="list-unstyled card pb-5">
      <h4 class="m-4">Followers</h4>

      <% @followers.each do |follower| %>
        <%= render 'follower', follower: follower %>
      <% end %>
    </ul>
  </div>
  <div class="col-3">
    <%= render 'posts/sidebar', user: current_user %>
  </div>
</div>

app/views/relationships/followings.html.erb
<div class="row">
  <div class="col-3">
    <%= render 'posts/user_card', user: current_user %>
  </div>
  <div class="col-6">
    <ul class="list-unstyled card pb-5">
      <h4 class="m-4">Following</h4>

      <% @followings.each do |following| %>
        <%= render 'following', following: following %>
      <% end %>
    </ul>
  </div>
  <div class="col-3">
    <%= render 'posts/sidebar', user: current_user %>
  </div>
</div>

app/views/relationships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Follower:</strong>
  <%= @relationship.follower %>
</p>

<p>
  <strong>User:</strong>
  <%= @relationship.user %>
</p>

<%= link_to 'Edit', edit_relationship_path(@relationship) %> |
<%= link_to 'Back', relationships_path %>

app/views/relationships/who_to_follow.html.erb
<div class="row">
  <div class="col-3">
  </div>
  <div class="col-6">
    <ul class="list-unstyled card pb-5">
      <h4 class="m-4">Who to follow</h4>

      <% @to_follows.each do |to_follow| %>
        <%= render 'to_follow', to_follow: to_follow %>
      <% end %>
    </ul>
  </div>
  <div class="col-3">
    <%= render 'posts/sidebar', user: current_user %>
  </div>
</div>