config/routes.rb
Rails.application.routes.draw do
  resources :reposts
  resources :likes
  root 'posts#index'
  resources :posts
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :relationships, only: [:index, :create, :destroy] do
    collection do
      get 'who_to_follow'
      get 'followers'
      get 'followings'
    end
  end
  get '/:username', to: 'posts#user_timeline', as: :user_timeline
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :reposts
  has_many :mentions

  after_save :save_mentions

  AT_REGEX = Regexp.new('(@([\w.@_-]+))', Regexp::EXTENDED)

  def liked_by_user?(user)
    likes.find_by(user_id: user.id)
  end

  def reposted_by_user?(user)
    reposts.find_by(user_id: user.id)
  end

  def save_mentions
    mentions = text.scan(AT_REGEX)
    users = mentions.map{|m| User.find_by(moniker: m[1,m.length])}.compact
    users.map{|u| u.mentions.create(post: self)}
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order('created_at DESC')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_url }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def user_timeline
    @user = User.find_by(moniker: params[:username])
    @posts = @user.posts
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:text, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def action_icon_color(action, post, user, color)
    case action
      when :like
        post.liked_by_user?(user) ? "color: #{color}" : ""
      else
        post.reposted_by_user?(user) ? "color: #{color}" : ""
    end
  end

  def linkify_mentions(text)
    mentions = text.scan(Post::AT_REGEX)
    mentions.each do |m|
      handle, moniker = m[0], m[1]
      timeline_path = user_timeline_path(username: moniker)
      text.sub!(handle, link_to(handle, timeline_path, style: "color: #009688;"))
    end
    text
  end

end

app/views/posts/_form.html.erb
<div style="
background: #0096880d;
    border: 1px solid #00800033;
" class="rounded">
  <%= form_for(post, :html => {class: 'align-items-end d-flex flex-column input-group p-2 pb-0'}) do |f| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.text_area :text, class: "form-control w-100", placeholder: "What's happening?", style: "font-size: 14px;", rows: "1" %>
    <%= f.submit class: "btn btn-outline-success mt-2", style: "font-size: 14px;" %>
  <% end %>
</div>

app/views/posts/_like_button.html.erb
<% unless post.liked_by_user?(current_user) %>
  <%= button_to(Like.new, {class: "btn pb-0 align-items-end d-flex flex-row mr-4", style: "font-size: 13px;color: #666;", params: {'like[user_id]' => current_user.id, 'like[post_id]' => post.id}}) do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 8 8" class="mr-1" style="<%= action_icon_color(:like, post, current_user, '#009688') %>">
      <path d="M2 0c-.55 0-1.04.23-1.41.59-.36.36-.59.85-.59 1.41 0 .55.23 1.04.59 1.41l3.41 3.41 3.41-3.41c.36-.36.59-.85.59-1.41 0-.55-.23-1.04-.59-1.41-.36-.36-.85-.59-1.41-.59-.55 0-1.04.23-1.41.59-.36.36-.59.85-.59 1.41 0-.55-.23-1.04-.59-1.41-.36-.36-.85-.59-1.41-.59z"
      />
    </svg>
    <%= post.likes.count %>
  <% end %>
<% else %>
  <%= button_to(Like.find_by(user: current_user, post: post), {method: :delete, class: "btn pb-0 align-items-end d-flex flex-row mr-4", style: "font-size: 13px;color: #666;"}) do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 8 8" class="mr-1" style="<%= action_icon_color(:like, post, current_user, '#009688') %>">
      <path d="M2 0c-.55 0-1.04.23-1.41.59-.36.36-.59.85-.59 1.41 0 .55.23 1.04.59 1.41l3.41 3.41 3.41-3.41c.36-.36.59-.85.59-1.41 0-.55-.23-1.04-.59-1.41-.36-.36-.85-.59-1.41-.59-.55 0-1.04.23-1.41.59-.36.36-.59.85-.59 1.41 0-.55-.23-1.04-.59-1.41-.36-.36-.85-.59-1.41-.59z"
      />
    </svg>
    <%= post.likes.count %>
  <% end %>
<% end %>

app/views/posts/_post.html.erb
<li class="media mt-2 px-3 pb-2" style="border-bottom: 1px solid rgba(0, 0, 0, 0.125);">
  <%= image_tag post.user.avatar_url(120), size: '40x40', class: 'mr-3 rounded-circle' %>
  <div class="media-body">
    <div>
      <span class="mt-0 mb-1 h6" style="
      font-size: 14px;
      "><%= link_to(post.user.fullname, user_timeline_path(post.user.moniker), style: "color: #009688;") %></span>
      <span class="text-muted"><%= link_to('@' + post.user.moniker, user_timeline_path(post.user.moniker), style: "color: #009688;") %>
        . <%= time_ago_in_words(post.created_at) %>
</span>
    </div>
    <%= linkify_mentions(post.text).html_safe %>
    <div class="actions mt-3 d-flex flex-row" style="
    font-size: 12px;
    ">
      <%= button_to({action: "create"}, {class: "btn pb-0 align-items-end d-flex flex-row mr-4", style: "font-size: 13px;color: #666;"}) do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="10" height="16" viewBox="0 0 8 8" class="mr-1">
          <path d="M.09 0c-.06 0-.09.04-.09.09v5.81c0 .05.04.09.09.09h5.91l2 2v-7.91c0-.06-.04-.09-.09-.09h-7.81z" transform="translate(0 -1.2)"/>
        </svg>
        555
      <% end %>
      <%= render 'repost_button', post: post %>
      <%= render 'like_button', post: post %>
    </div>
  </div>
</li>

app/views/posts/_repost_button.html.erb
<% unless post.reposted_by_user?(current_user) %>
  <%= button_to(Repost.new, {class: "btn pb-0 align-items-end d-flex flex-row mr-4", style: "font-size: 13px;color: #666;", params: {'repost[user_id]' => current_user.id, 'repost[post_id]' => post.id}}) do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 8 8" class="mr-1" style="<%= action_icon_color(:repost, post, current_user, '#009688') %>">
      <path d="M6 0v1h-5c-.55 0-1 .45-1 1v1h1v-1h5v1l2-1.5-2-1.5zm-4 4l-2 1.5 2 1.5v-1h5c.55 0 1-.45 1-1v-1h-1v1h-5v-1z" transform="translate(0 -0.5)"/>
    </svg>
    <%= post.reposts.count %>
  <% end %>
<% else %>
  <%= button_to(Repost.find_by(user: current_user, post: post), {method: :delete, class: "btn pb-0 align-items-end d-flex flex-row mr-4", style: "font-size: 13px;color: #666;"}) do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 8 8" class="mr-1" style="<%= action_icon_color(:repost, post, current_user, '#009688') %>">
      <path d="M6 0v1h-5c-.55 0-1 .45-1 1v1h1v-1h5v1l2-1.5-2-1.5zm-4 4l-2 1.5 2 1.5v-1h5c.55 0 1-.45 1-1v-1h-1v1h-5v-1z" transform="translate(0 -0.5)"/>
    </svg>
    <%= post.reposts.count %>
  <% end %>
<% end %>

app/views/posts/_sidebar.html.erb
<div class="card">
  <div class="card-body">
    <div><span class="h6">Who to follow</span> .
      <span class="small">
        <a href="#" style="color: #009688;">Refresh</a> ·
        <%= link_to "View all", who_to_follow_relationships_path, style: "color: #009688;" %>
      </span>
    </div>
  </div>
  <ul class="list-group list-group-flush">
    <% user.who_to_follow.each do |u| %>
      <%= render 'posts/who_to_follow_sidebar', user_to_follow: u %>
    <% end %>
  </ul>
</div>

<div class="card mt-3">
  <div class="card-body">
    © 2018 Mayowa Yakub
  </div>
</div>

app/views/posts/_user_card.html.erb
<div class="align-items-center card">
  <%= image_tag user.avatar_url(384), class: 'mt-2 rounded-circle', style: "
    width: 128px;
    height: 128px;
" %>
  <h6 class="mb-0 mt-2"><%= user.fullname %></h6>
  <p>@<%= user.moniker %></p>

  <div class="px-3 w-100">
    <p class="card-text text-center"><%= user.description %></p>
  </div>

  <div class="d-flex mb-4 mt-2">
    <%= link_to root_url, class: "align-items-center card-link d-flex flex-column", style: "color: #009688;" do %>
      <p class="my-0">Posts</p><%= user.posts.count %>
    <% end %>
    <%= link_to followers_relationships_url, class: "align-items-center card-link d-flex flex-column", style: "color: #009688;" do %>
      <p class="my-0">Followers</p><%= user.followers.count %>
    <% end %>
    <%= link_to followings_relationships_url, class: "align-items-center card-link d-flex flex-column", style: "color: #009688;" do %>
      <p class="my-0">Following</p><%= user.followings.count %>
    <% end %>
  </div>
  <div class="mb-4 mt-2 px-3 text-center w-100">
    <% unless user.id == current_user.id %>
      <!--TODO: Won't scale-->
      <% unless current_user.followings.pluck(:id).include?(user.id) %>
        <%= form_for Relationship.new(user_id: user.id, follower_id: current_user.id) do |f| %>
          <%= f.hidden_field :user_id %>
          <%= f.hidden_field :follower_id %>
          <%= f.submit("Follow", class: "btn btn-outline-success py-0 mt-2", style: "border-radius: 1rem; font-size: 13px;") %>
        <% end %>

      <% else %>

        <%= form_for Relationship.find_by!(user_id: user.id, follower_id: current_user.id), method: :delete do |f| %>
          <%= f.hidden_field :user_id %>
          <%= f.hidden_field :follower_id %>
          <%= f.submit("Following", class: "btn btn-outline-danger py-0 mt-2", style: "border-radius: 1rem; font-size: 13px;") %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/_who_to_follow.html.erb
<li class="list-group-item">
  <div class="media">
    <%= image_tag user_to_follow.avatar_url(120), size: '40x40', class: 'mr-3 rounded-circle' %>
    <div class="media-body">
      <h6 class="h mb-0 mt-0" style="
      font-size: 14px;
      "><%= user_to_follow.fullname %></h6>

      <%= form_for Relationship.new(user_id: user_to_follow.id, follower_id: current_user.id) do |f| %>
        <%= f.hidden_field :user_id %>
        <%= f.hidden_field :follower_id %>
        <%= f.submit("Follow", class: "btn btn-outline-primary py-0 mt-2", style: "border-radius: 1rem; font-size: 10px;") %>
      <% end %>

    </div>
  </div>
</li>

app/views/posts/_who_to_follow_sidebar.html.erb
<li class="list-group-item">
  <div class="media">
    <%= image_tag user_to_follow.avatar_url(120), size: '40x40', class: 'mr-3 rounded-circle' %>
    <div class="media-body">
      <h6 class="h mb-0 mt-0" style="
      font-size: 14px;
      "><%= link_to(user_to_follow.fullname, user_timeline_path(user_to_follow.moniker), style: "color: #009688;") %></h6>

      <%= form_for Relationship.new(user_id: user_to_follow.id, follower_id: current_user.id) do |f| %>
        <%= f.hidden_field :user_id %>
        <%= f.hidden_field :follower_id %>
        <%= f.submit("Follow", class: "btn btn-outline-success py-0 mt-2", style: "border-radius: 1rem; font-size: 10px;") %>
      <% end %>

    </div>
  </div>
</li>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-3">
    <%= render 'user_card', user: current_user %>
  </div>
  <div class="col-6">
    <ul class="list-unstyled card pb-5">
      <%= render "form", post: current_user.posts.new %>
      <%= render @posts %>
    </ul>
  </div>
  <div class="col-3">
    <%= render 'sidebar', user: current_user %>
  </div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/user_timeline.html.erb
<div class="row">
  <div class="col-3">
    <%= render 'user_card', user: @user %>
  </div>
  <div class="col-6">
    <ul class="list-unstyled card pb-5">
        <%= render @posts %>
    </ul>
  </div>
  <div class="col-3">
    <%= render 'sidebar', user: current_user %>
  </div>
</div>